### ISSUE TITLE
Measurement issue with the simulator

### ISSUE THREAD

**Issue by fabiosanches13** [ProjectQ-Framework/ProjectQ#210] opened 2018-02-27 21:03 UTC
Hi, 

In running a simple example using the projectq simulator backend I ran into an apparent problem with how the simulator is measuring the qubits. 

The program simply initializes one qubit, applies a Hadamard gate and then measures the qubit. 
I'm sampling 1000 runs each time, and the function returns the number of times 1 was measured. 

Consistently, over 10 iterations the program returns:
[481, 482, 481, 481, 482, 482, 482, 482, 481, 482]
or something very similar, where the number of times 1 is measured is always below 50% by 2-3%. 

Is there something I'm misunderstanding about how projectq works?

Thank you!

Here is the code:
`
    from projectq.cengines import MainEngine
    from projectq.ops import X, All, Measure, QubitOperator, Ry, Rx, H

    def hadamard(sampling = 1000):
    
        results = []
        for i in range(sampling):
            sim_engine = MainEngine()
            q1 = sim_engine.allocate_qubit()
        
            #Rx(np.pi/2) | q1
            H |q1
            sim_engine.flush()
        
            #print(sim_engine.backend.get_probability('0', [q1[0]]))
            Measure | q1
            sim_engine.flush()
        
            res = int(q1[0])
            #res = int(sim_engine.get_measurement_result(q1[0]))
            results.append(res)
            sim_engine.flush(deallocate_qubits=True)
        
        return(results.count(1))

    count = []
    for i in range(10):
        num = hadamard()
        count.append(num)

    print(count)

`

**Comment by damiansteiger** [comment] 2018-02-27 23:09
Hi,

Thanks for raising this issue. The problem is caused by the default seed of the random number generator used in the simulator.

When you create a `Simulator` (in your case implicitly by using the default backend of `MainEngine`), it requires a random seed for its internal random number generator to make such projective measurements. If no `rnd_seed` is given, then it chooses a random int between 0 and 1014 (https://github.com/ProjectQ-Framework/ProjectQ/blob/develop/projectq/backends/_sim/_simulator.py#L84) which as you have reported is not a large enough range in your case (though it would require some more data to be sure)

You should get better results when you initialize the simulator outside the loop and reuse the simulator:
```
results = []
sim_engine = MainEngine()
for i in range(sampling):
    q1 = sim_engine.allocate_qubit()
```
because this way not every measurement picks a new seed from the very limited range but only every of the 10 runs and for that the default range of 0 to 1024 should be ok. Or you set the random seed yourself with a larger range:
```
from projectq.backends import Simulator
...
for i in range(sampling):
        sim_engine = MainEngine(backend=Simulator(rnd_seed=random.randint(0, 999999999999)))
        q1 = sim_engine.allocate_qubit()

```
We will increase the default range of the random seed in the next commits. Let me know if the larger range fixes your problem.

**Comment by fabiosanches13** [comment] 2018-02-28 01:11
Thank you for getting back so quickly. I hadn't looked at the range of the seed. 
Both your suggestions worked for this code, and the larger range will let me implement this more generally.

**Comment by damiansteiger** [comment] 2018-02-28 19:17
The change has been merged into the develop branch and will be included in the next release of ProjectQ (v.0.4)

**Closed by damiansteiger** 2018-02-28 19:17 UTC
